name: ecocor
services:
  api:
    image: "ecocor-api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_SERVER=http://extractor
        - GITHUB_WEBHOOK_SECRET=qwerty
    environment:
      - EXIST_PASSWORD=
      - ECOCOR_API_BASE=http://localhost:8090/exist/restxq/ecocor
    ports:
      - "8090:8080"
  extractor:
    build: https://github.com/dh-network/ecocor-extractor.git#main
    ports:
      - "8040:80"
